TEAMS_BY_SPORT = {
    "AFL": [
        "Adelaide Crows",
        "Brisbane Lions",
        "Carlton Blues",
        "Collingwood Magpies",
        "Essendon Bombers",
        "Fremantle Dockers",
        "Geelong Cats",
        "Gold Coast Suns",
        "Greater Western Sydney Giants",
        "Hawthorn Hawks",
        "Melbourne Demons",
        "North Melbourne Kangaroos",
        "Port Adelaide Power",
        "Richmond Tigers",
        "St Kilda Saints",
        "Sydney Swans",
        "West Coast Eagles",
        "Western Bulldogs",
    ],
    "NRL": [
        "Brisbane Broncos",
        "Canberra Raiders",
        "Canterbury Bulldogs",
        "Cronulla Sharks",
        "Gold Coast Titans",
        "Manly Sea Eagles",
        "Melbourne Storm",
        "New Zealand Warriors",
        "Newcastle Knights",
        "North Queensland Cowboys",
        "Parramatta Eels",
        "Penrith Panthers",
        "South Sydney Rabbitohs",
        "St George Illawarra Dragons",
        "Sydney Roosters",
        "Wests Tigers",
    ],
    "Soccer": [
        "Arsenal",
        "Aston Villa",
        "Bournemouth",
        "Brentford",
        "Brighton",
        "Burnley",
        "Chelsea",
        "Crystal Palace",
        "Everton",
        "Fulham",
        "Liverpool",
        "Luton Town",
        "Manchester City",
        "Manchester United",
        "Newcastle",
        "Nottingham Forest",
        "Sheffield United",
        "Tottenham",
        "West Ham",
        "Wolves",
        "Real Madrid",
        "Barcelona",
        "Atletico Madrid",
        "Sevilla",
        "Valencia",
        "Bayern Munich",
        "Borussia Dortmund",
        "RB Leipzig",
        "Union Berlin",
        "Borussia Monchengladbach",
        "Juventus",
        "Inter Milan",
        "AC Milan",
        "Roma",
        "Napoli",
    ],
    "Basketball": [
        "Atlanta Hawks",
        "Boston Celtics",
        "Brooklyn Nets",
        "Charlotte Hornets",
        "Chicago Bulls",
        "Cleveland Cavaliers",
        "Dallas Mavericks",
        "Denver Nuggets",
        "Detroit Pistons",
        "Golden State Warriors",
        "Houston Rockets",
        "Indiana Pacers",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Memphis Grizzlies",
        "Miami Heat",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "New Orleans Pelicans",
        "New York Knicks",
        "Oklahoma City Thunder",
        "Orlando Magic",
        "Philadelphia 76ers",
        "Phoenix Suns",
        "Portland Trail Blazers",
        "Sacramento Kings",
        "San Antonio Spurs",
        "Toronto Raptors",
        "Utah Jazz",
        "Washington Wizards",
    ],
    "Cricket": [
        "Brisbane Heat",
        "Adelaide Strikers",
        "Sydney Sixers",
        "Sydney Thunder",
        "Melbourne Renegades",
        "Melbourne Stars",
        "Hobart Hurricanes",
        "Perth Scorchers",
        "Australia",
        "India",
        "England",
        "New Zealand",
        "Pakistan",
        "South Africa",
        "West Indies",
        "Sri Lanka",
    ],
}


BET_TYPE_KEYWORDS = {
    "Same Game Multi": ["same game multi", "sgm"],
    "Multi": ["multibet", "multi"],
    "Exotic": ["trifecta", "first 4", "exacta", "quinella", "quaddie", "boxed"],
}
